name: Doctests

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  doctests:
    # Should we run doctests on all platforms?
    name: Run Doctests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install doxygen
        run: |
          sudo apt update
          sudo apt install -y doxygen

      - name: Build
        shell: bash
        run: |
          python -m pip install sphinx sphinx_rtd_theme numpy numpydoc
          cmake -B build/docs -S documentation -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build/docs --config $BUILD_TYPE

      - name: Run Doctests
        run: cmake --build build/docs --target pydoctest --config $BUILD_TYPE
