name: Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and publish documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doxygen
        run: brew install doxygen

      - name: Build
        run: |
          cmake -B build/docs -S documentation
          cmake --build build/docs --target cppdocs

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/doxygen/html
