name: Tests

on: [push, pull_request]

env:
  CMAKE_VERSION: 3.16.2
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        # TODO test for more python versions
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure CMake for tests
      shell: bash
      working-directory: ${{runner.workspace}}/daylight
      run: cmake -B build/test -S test -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/daylight
      shell: bash
      run: cmake --build build/test --config $BUILD_TYPE

    - name: Run Unit Tests
      working-directory: ${{runner.workspace}}/daylight/build/test
      shell: bash
      run: ctest --output-on-failure -C $BUILD_TYPE

    - name: Test python bindings
      working-directory: ${{runner.workspace}}/daylight/test/python
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytz numpy
        python test.py
